spring:
  profiles:
    active:
      - local
    group:
      local:
        - common
      prod:
        - common
default:
  string: default property
---
spring:
  config:
    active:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/pinterest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.hbm2ddl.auto: update
  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${hostname}:${port}/${dbname}
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

